project:
  type: book
  
bibliography: _bibliography.bib
nocite: |
  @*
  

book:
  title: "Housing Insecurity and Homelessness in New York State"
  author: "Don Boyd"
  date: today
  date-format: long
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Housing Insecurity"
      chapters:
      - measure_insecurity.qmd
      - recent_events_housing.qmd
    - part: "Homelessness"      
    - conclusions.qmd
    - references.qmd

format:
  html:
    theme: cosmo
  # pdf:
  #   documentclass: scrreprt
  
# web 
#   site: https://osc-housing.netlify.app/
#   password: oscdjb




