project:
  type: book
  output-dir: _report
  
book:
  title: "Housing Insecurity in New York State"
  author: "Don Boyd"
  date: today
  date-format: long
  chapters:
    - index.qmd
    - highlights.qmd
    - intro.qmd
    - part: "Housing Insecurity"
      chapters:
      - insecurity/housing_insecurity.qmd
      # - insecurity/owners_renters.qmd
      - insecurity/cost_and_affordability.qmd
      # - insecurity/housing_cost_burden.qmd
      # - insecurity/housing_affordability.qmd      
      - insecurity/quality.qmd
      - insecurity/stress.qmd
      # - insecurity/measure_homelessness.qmd
      - insecurity/recent_events_housing.qmd
    - part: "Policies to address housing insecurity"
      chapters: 
      - policies/policy_intro.qmd
      - policies/federal.qmd
      - policies/state.qmd
    - conclusions.qmd
    - bibliography.qmd
    - part: "Appendix"
      chapters: 
        - appendix/appendix.qmd
    - part: "Notes"
      chapters: 
      - notes/notes.qmd
      - notes/articles.qmd
      - notes/housing_insecurity_notes.qmd
      - notes/housing_cost_burden_notes.qmd
      - notes/housing_forced_removal_notes.qmd
      - notes/mortgage_delinquencies.qmd
  
bibliography: _bibliography.bib
nocite: |
  @*
  
# https://quarto.org/docs/computations/execution-options.html
# warning: false
# error: false
execute:
  echo: false
  message: false
  warning: false
  note: false

format:
  html:
    theme: cosmo
  # pdf:
  #   documentclass: scrreprt
  
# web 
#   site: https://osc-housing.netlify.app/
#   password: oscdjb




