project:
  type: book
  output-dir: _report
  
editor_options: 
  chunk_output_type: console

# https://quarto.org/docs/computations/execution-options.html
# warning: false
# error: false
execute:
  echo: false
  message: false
  warning: false
  note: false

# output
# quarto render document.qmd --to html
# quarto render --to pdf
# quarto publish netlify --no-render --no-browser --no-prompt
# quarto publish netlify --no-browser --no-prompt
# web 
#   site: https://osc-housing.netlify.app/
#   password: oscdjb
format:
  html:
    theme: cosmo
    toc-depth: 4
  # docx:
  #   toc: true
  #   toc-depth: 2
  #   number-sections: true
  #   highlight-style: github
  #   # reference-doc: refdoc.docx
  # pdf:
  #   toc: true
  #   toc-depth: 2
  #   documentclass: report
# scrreprt scrartcl report  
  
book:
  title: "Housing Insecurity in New York State"
  author: "Don Boyd"
  date: today
  date-format: long
  chapters:
    - index.qmd
    - todo.qmd  # delete when done
    - execsum.qmd
    - part: "Housing Insecurity"
      chapters:
        - insecurity/housing_insecurity.qmd
        - insecurity/cost/cost.qmd
        - insecurity/quality/quality.qmd
        - insecurity/stress/stress.qmd
        - insecurity/homelessness/homelessness.qmd
        - insecurity/crosscutting.qmd
        - insecurity/trends.qmd
    - part: "Policies to Address Housing Insecurity"
      chapters:
        - policies/policy_intro.qmd
        - policies/federal.qmd
    #   - policies/state.qmd
    - conclusions.qmd
    - bibliography.qmd
    - part: "Appendix"
      # - insecurity/recent_events_housing.qmd    
      chapters: 
        - appendix/appendix.qmd
    # - part: "Notes"
    #   chapters: 
    #   - notes/notes.qmd
    #   - notes/articles.qmd
    #   - notes/housing_insecurity_notes.qmd
    #   - notes/housing_cost_burden_notes.qmd
    #   - notes/housing_forced_removal_notes.qmd
    #   - notes/mortgage_delinquencies.qmd
  
bibliography: _bibliography.bib
nocite: |
  @*
  


  

