project:
  type: book
  
bibliography: _bibliography.bib
nocite: |
  @*
  

book:
  title: "Housing Insecurity and Homelessness in New York State"
  author: "Don Boyd"
  date: today
  date-format: long
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Housing Insecurity"
      chapters:
      - measure_housing_insecurity.qmd
      - housing_affordability.qmd
      - recent_events_housing.qmd
    - part: "Homelessness"
      chapters: 
      - measure_homelessness.qmd
    - conclusions.qmd
    - references.qmd
    - part: "Appendix and Working Notes"
      chapters: 
        - housing_cost_burden_notes.qmd

# https://quarto.org/docs/computations/execution-options.html
# warning: false
# error: false
execute:
  echo: false
  message: false
  note: false

format:
  html:
    theme: cosmo
  # pdf:
  #   documentclass: scrreprt
  
# web 
#   site: https://osc-housing.netlify.app/
#   password: oscdjb




