Adequate housing is essential to people's physical, social and psychological well-being. High housing costs relative to income, substandard or overcrowded housing, and stress related to these issues can lead to greater incidence of physical and mental health problems, and greater health care costs. These challenges often are particularly severe for children.

## High housing cost burden in New York

Housing insecurity has many dimensions. A particularly important one is high cost relative to income, which we discuss here. The body of the report examines additional dimensions and measures of housing insecurity. \*\[M&T: for the summary, I'm thinking maybe just mention housing cost burden. However, if you think we need other dimensions, too, that is possible. It is also possible to have a summary measure, but I don't think that's a good idea.\]\*

Over \[2.6\] million households in New York State have housing costs that exceed 30 percent of income. This amounts to \[36%\] of New York households, making us the fourth-highest housing cost burden state, after \[California, Hawaii, and New Jersey\].

High costs are particularly common among renters: \[47.2\] percent of New York renter households have housing costs that exceed 30 percent of income, compared to \[26.4\] percent of New York homeowner households.

High housing costs are most prevalent among low-income households and among people of color. \[key facts to come\]

High housing costs relative to income are far more common in New York City than in the rest of the state, in part because of the extraordinarily high real estate prices and in part because two-thirds of New York City households are renter households. of housing in

## Policies to address housing insecurity

\[TO COME\]
