# Evictions in New York

## Data notes

### What is an eviction case?

> Eviction cases are civil lawsuits filed by landlords to remove tenants from rental properties or collect past-due rent or other monetary damages (1). The filing represents only the first action in the formal eviction process. Tenants must respond to the filing, either by answering the summons or appearing in court. If the tenant fails to respond, a default judgment in favor of the plaintiff is usually issued by the court. If the tenant responds, the case proceeds and can be resolved in many ways. The case may be dismissed due to insufficient action or evidence by the landlord or because the tenant has already vacated the property. The landlord and tenant may resolve the dispute by mutual agreement, which may or may not stipulate that the tenant vacates the property or repays past-due rent. A judge may decide the case in favor of the landlord or tenant after a court trial. If a tenant is ordered by the court to vacate a property but does not leave voluntarily, the landlord can file a writ of restitution with the sheriff or marshal to forcibly remove the tenant. [@ashleygromisSupplementaryInformationEstimating2022]
