# Update {.unnumbered}

I've defined 4 broad categories of housing insecurity. The idea is to use the best measures for each. Here are the categories and examples of what I'm including:

-   Housing cost and availability

    -   Housing cost burden

    -   Housing affordability (more to come)

    -   Possibly: vacancy rates, rapid price or mortgage rate rises, or other measures of challenging housing markets

-   Housing quality and conditions

    -   Lack of complete plumbing and kitchen facilities

    -   Crowding (persons per room)

    -   HUD also uses data on year structure was built but I'm thinking that's probably not worth the effort.

-   Housing-related stress

    -   Eviction and threat of eviction (MSA; would prefer county level data - it's clear there are big variations within regions)

    -   Mortgage delinquencies, if there is a good substate source (FRBNY does have county-level estimates of total consumer debt ratio to income)

    -   Foreclosures

-   Homelessness

I do want to look across these categories as well as within each. There are some interesting geographic variations.

As for who has housing insecurity, other than geographic variation - for example, variation by race/ethnicity, and income - I'm thinking the most practical way to address this is to use HUD's combined housing problems category and examine across race/ethnicity, income, disability status, elderly status.

Analysis

-   I'm still at the exploratory stage. I've pumped out a lot of tables, mostly related to housing cost and housing quality/conditions. Not much real analysis yet.

-   I'll start narrowing down after back from vacation, analyze the data, and of course begin description and analysis of policies.

Policies

-   I want to develp a summary table to help organize the analysis. I want to categorize policies, perhaps identifying the kinds of policies that address each of the 3 main categories of housing insecurity above.

-   The organization of the table might be something like this:

-   Rows

    -   A group of rows for federal policies, followed by

    -   A group of rows for state policies

-   Columns

    -   Policy name

    -   Statewide \$ amount, recent year

    -   4 columns for the kinds of insecurities addressed: cost, quality, housing-related stress, homelessness

-   Cells - For each policy, there will be up to 2 sentences in each of the 4 columns, describing how the policy addresses a particular kind of insecurity.

I think this will help think about how the money matches up with the kinds of insecurity.

Have gathered some data on policies, have not done much with it.

As you look through the data you'll see some outliers. Based on spot checking, many of the outliers appear to be special situations:

-   Communities with a large share of college students (e.g., Ithaca, and Tompkins County)

-   At least one community with high concentrations of Amish residents, and one with high concentrations of Hasidic Jews (e.g, Kiryas Joel, coterminous with the town of Palm Tree in Orange County).

-   A relatively rich community in Nassau County (North Hills) where a large share of rental apartments do not have complete plumbing or kitchen facilities; it's not clear yet why this is so. It could be a bad number due to a relatively small number of rental units, or it could be something else.

I'll have to keep these kinds of issues in mind as I get to the writing stage to avoid writing about spurious issues.
