---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Trends in housing cost burden

```{r}
#| label: setup
#| include: false

source(here::here("r", "libraries.r"))
source(here::here("r", "functions.r"))
source(here::here("r", "constants.r"))

dacs <- here::here("data", "acs")

tabshells <- readRDS(path(dacs, "tabshells_2019.rds"))

```

```{r}
#| label: get-rent-burden
#| include: false

# rent burden
vtab("B25070")

b25070ts <- readRDS(here::here("data", "acs", "B25070_timeseries.rds"))
rentcb <- b25070ts |>
  select(geoid, geotype, name, endyear, variable, estimate) |> 
  pivot_wider(names_from = variable, values_from = estimate) |> 
  mutate(rentcb30=(B25070_007 + B25070_008 + B25070_009 + B25070_010) / (B25070_001 - B25070_011),
         rentcb30b=(B25070_007 + B25070_008 + B25070_009 + B25070_010) / B25070_001)


```

```{r}
#| label: get-owner-mortgage-burden
#| include: false

vtab("B25091")
b25091ts <- readRDS(here::here("data", "acs", "B25091_timeseries.rds"))
glimpse(b25091ts)

ownmcb <- b25091ts |>
  select(geoid, geotype, name, endyear, variable, estimate) |> 
  pivot_wider(names_from = variable, values_from = estimate) |> 
  mutate(ownmcb30=(B25091_008 + B25091_009 + B25091_010 + B25091_011) / (B25091_002 - B25091_012))
glimpse(ownmcb)

```


```{r}
#| label: plot
#| fig-width: 12
#| fig-height: 8
#| fig-column: page-right
#| include: true

pdata <- bind_rows(rentcb |> 
                  select(geoid, geotype, name, endyear, value=rentcb30) |> 
                  mutate(tenure="renter"),
                ownmcb |> 
                  select(geoid, geotype, name, endyear, value=ownmcb30) |> 
                  mutate(tenure="owner")) |> 
  mutate(geotypef=factor(geotype, 
                         levels=c("nation", "state"),
                         labels=c("United States", "New York")),
         tenuref=factor(tenure, 
                        levels=c("owner", "renter"),
                        labels=c("Owners of houses with mortgages", "Renters")))

p <- pdata |> 
  filter((geotype=="nation") |
           (geotype=="state" & geoid=="36")) |> 
  ggplot(aes(endyear, value, colour=geotypef)) +
  geom_line() +
  geom_point() +
  scale_colour_manual(values=c("blue", "darkgreen")) +
  scale_y_continuous(name="Percentage of household income",
                     limits=c(0, NA), 
                     breaks=seq(0, 1, 0.05),
                     labels=scales::percent_format(accuracy=1)) +
  scale_x_continuous(name=NULL, breaks=seq(2000, 2020, 2)) +
  labs(caption = "Source: American Community Survey, Annual, Tables B25070 and B25091") +
  ggtitle("Housing costs as percentage of household income") +
  facet_wrap(~tenuref) +
  theme_bw() +
  caption_left  +
  theme(legend.position = 'bottom') +
  legend_notitle
p

```


```{r}
#| eval: false
#| include: false
#| label: OLD-chas

chdir <- here::here("data", "chas")
chdir2019 <- path(chdir, "2015-2019")

# cost <- readRDS(here::here("data", "cost.rds"))

t9 <- readRDS(path(chdir2019, "t9long.rds"))
# we need cnty, cntyname maybe shortname also

# use allrace for this set of tables
cost_wide <- t9 |> 
  filter(race=="allrace") |> 
  # filter(nytype=="state", stabbr=="NY") |> # uncomment for testing
  pivot_wider(names_from = c(tenure, cost)) |> 
  # get own and rent sums where cost burden is computable
  mutate(own_check=own_costle30 + own_costgt30le50 + own_costgt50,
         rent_check=rent_costle30 + rent_costgt30le50 + rent_costgt50,
         own_cost30=own_costgt30le50 + own_costgt50,
         rent_cost30=rent_costgt30le50 + rent_costgt50,
         alltenure_cost30=own_cost30 + rent_cost30,
         own_cost50=own_costgt50,
         rent_cost50=rent_costgt50,
         alltenure_cost50=own_cost50 + rent_cost50) |> 
  relocate(own_check, rent_check, .after=cntyname) |> 
  # calc percentages
  mutate(own_pct30=own_cost30 / own_allcost,
         rent_pct30=rent_cost30 / rent_allcost,
         alltenure_pct30=alltenure_cost30 / alltenure_allcost,
         own_pct50=own_cost50 / own_allcost,
         rent_pct50=rent_cost50 / rent_allcost,
         alltenure_pct50=alltenure_cost50 / alltenure_allcost, 
         renter_share=rent_allcost / alltenure_allcost)

# tabdata for all types
# nytype groups: state, region, county, city, town, village
tabdata <- cost_wide |> 
  filter(nytype %in% c("state", "region", "county", "city", "town", "village")) |>
  rename(allunits=alltenure_allcost,
         own_pct=own_pct30, rent_pct=rent_pct30, alltenure_pct=alltenure_pct30) |> 
  group_by(nytype) |> 
  mutate(ownrank=row_number(desc(own_pct)),
         rentrank=row_number(desc(rent_pct)),
         alltenurerank=row_number(desc(alltenure_pct)))  |> 
  select(nytype, stabbr, mininame, cntyname, 
         allunits,
         own_pct, rent_pct, alltenure_pct, 
         ownrank, rentrank, alltenurerank,
         renter_share) |> 
  ungroup() |> 
  arrange(desc(alltenure_pct))
```

