# Policies to address housing insecurity

Describe and categorize the different kinds of policies and the dimensions of housing insecurity that they address.


Fed Reserve article

EVICTION DIVERSION
The State of New York extended its eviction moratorium for COVID-related residential and
commercial evictions until January 15, 2022. New York’s eviction protections for renters
impacted by the pandemic are now one of the most expansive in the nation.23 Although the state,
like many others, has struggled to disburse billions of dollars in rent relief, the extended eviction
protections will potentially keep hundreds of thousands of struggling residents in their homes
while they await emergency rental assistance. As of August 31, 2021, New York has obligated
or distributed more than $1.2 billion in funding, including more than $300 million in direct
payments to more than 23,000 landlords.24
The City of Philadelphia rolled out a robust Eviction Diversion Program, which involves
mediation between landlords and tenants before an eviction can proceed.25 Eviction diversion
programs not only keep parties out of costly court hearings, they also encourage reluctant
or unaware tenants and landlords to access rent relief. A roundtable participant commented
that the availability of rental assistance funds allowed for the City of Philadelphia to work in
partnership with local court systems to address issues around nonpayment and avert evictions.
As of July 2021, 91.2% of households that completed Philadelphia’s mediation program avoided
an eviction proceeding.26