---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Housing cost and availability

{{< include housing_cost_burden.qmd >}}

{{< include housing_affordability.qmd >}}


## Availability and other market measures - data sources under investigation

### FHFA housing prices

-   [FHFA](https://www.fhfa.gov/DataTools/Downloads/Pages/House-Price-Index-Datasets.asp) All-Transactions House Price Index, [FRED](https://fred.stlouisfed.org/series/ATNHPIUS36001A)

    -   Counties (Developmental Index; Not Seasonally Adjusted) -- Annual House Price Indexes (see Working Papers 16-01, 16-02, and 16-04)
    
At the end I show price change since 2016.

### Census building permits

Monthly and annual to the county level.

https://www.census.gov/construction/bps/
https://www2.census.gov/econ/bps/


### Realtor.com

> Data Attribution: Files in the realtor.com real estate data library are free to use, we just ask that you attribute any full or partial use of the data to realtor.com with a link to this page. See specific notes on attribution for each data series...

Several county-level data sets

    -  Monthly inventory: active for-sale listings (including median list price, average list price, luxury list price, median days on market, average days on market, total active listings, new listings, price increases, price reductions).
    
    -  Market Hotness Index: scores and rankings based on days on market (supply index) and realtor.com views per property (demand index).


## Selected data (exploratory at this point)

{{< include prices.qmd >}}


